export const GET_CATEGORIES_LIST_LOADING = "GET_CATEGORIES_LIST_LOADING";
export const GET_CATEGORIES_LIST_SUCCESS = "GET_CATEGORIES_LIST_SUCCESS";
export const GET_CATEGORIES_LIST_FAIL = "GET_CATEGORIES_LIST_FAIL";


