export const GET_CATEGORIES_DETAIL_LOADING = "GET_CATEGORIES_DETAIL_LOADING";
export const GET_CATEGORIES_DETAIL_SUCCESS = "GET_CATEGORIES_DETAIL_SUCCESS";
export const GET_CATEGORIES_DETAIL_FAIL = "GET_CATEGORIES_DETAIL_FAIL";
